title: "Paul Jordan's Portfolio"
description: "Aspiring Cybersecurity Professional looking to showcase my skills to a future employer."
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
